version: '3.1'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: batch
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      TZ: Asia/Seoul
    ports:
      - "44532:5432"
    volumes:
#      - ./.var/lib/postgresql/data:/var/lib/postgresql/data
      - ./00_init.sql:/docker-entrypoint-initdb.d/00_init.sql

#  storage:
#    image: minio/minio:latest
#    container_name: minio
#    restart: always
#    command: server /data --console-address ":9001"
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    environment:
#      MINIO_ROOT_USER: minioadmin
#      MINIO_ROOT_PASSWORD: minioadmin
#
#    volumes:
#      - ./.blob/minio/data:/data