spring:
  datasource:
    hikari.maximum-pool-size: 10
    url: jdbc:postgresql://localhost:54532/batch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
    username: root
    password: password

  batch:
    jdbc:
      initialize-schema: always
